// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_ContratacionEmpleados.DAL;

namespace ProyectoFinal_ContratacionEmpleados.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211114193111_Añadiendo entidad instructores")]
    partial class Añadiendoentidadinstructores
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ProyectoFinal_ContratacionEmpleados.Entidades.Instructores", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidosInstructor")
                        .HasColumnType("TEXT");

                    b.Property<int>("CantidadEmpleados")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInstructor")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreInstructor")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoInstructor")
                        .HasColumnType("TEXT");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructores");
                });

            modelBuilder.Entity("ProyectoFinal_ContratacionEmpleados.Entidades.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistroUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoFinal_ContratacionEmpleados.Entidades.Vacantes", b =>
                {
                    b.Property<int>("VacanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionVacante")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDeRegistroVacante")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDeVacante")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequisitosVacante")
                        .HasColumnType("TEXT");

                    b.HasKey("VacanteId");

                    b.ToTable("Vacantes");
                });
#pragma warning restore 612, 618
        }
    }
}
