// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_ContratacionEmpleados.DAL;

namespace ProyectoFinal_ContratacionEmpleados.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ProyectoFinal_ContratacionEmpleados.Entidades.Vacantes", b =>
                {
                    b.Property<int>("VacanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionVacante")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDeRegistroVacante")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDeVacante")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequisitosVacante")
                        .HasColumnType("TEXT");

                    b.HasKey("VacanteId");

                    b.ToTable("Vacantes");
                });
#pragma warning restore 612, 618
        }
    }
}
